name: adoptrix-deps

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'sup3rSECRET!'
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
    driver: local
