name: adoptrix-deps

services:
  # SQL Server 2022 Developer Edition
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "sup3rSECRET!"
    entrypoint: /usr/config/entrypoint.sh
    ports:
      - 1433:1433
    volumes:
      - ./scripts:/usr/config:ro
      - sql-server-data:/var/opt/mssql

  # Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - storage-data:/data

volumes:
  sql-server-data:
    driver: local
  storage-data:
    driver: local
