name: adoptrix-deps

services:
  # SQL Server 2022 Developer Edition
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'sup3rSECRET!'
    ports:
      - 1433:1433
    volumes:
      - adoptrix-sql-server-data:/var/opt/mssql

  # Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - azurite-data:/data

volumes:
  adoptrix-sql-server-data:
    external: true
  azurite-data:
    driver: local
