// <auto-generated />
using System;
using Adoptrix.Database.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adoptrix.Database.Migrations
{
    [DbContext(typeof(AdoptrixDbContext))]
    [Migration("20240318065746_AnimalNonNullable")]
    partial class AnimalNonNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adoptrix.Core.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<char>("Sex")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Adoptrix.Core.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SpeciesId");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e719fea1-14d5-45a3-845d-404c88c4549f"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Labrador Retriever",
                            SpeciesId = new Guid("f2d44dc6-6c6c-41d0-ad8d-e6c814b09c1a")
                        },
                        new
                        {
                            Id = new Guid("9b2ace0b-fb18-4da4-86a5-c7404cfbf145"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "German Shepherd",
                            SpeciesId = new Guid("f2d44dc6-6c6c-41d0-ad8d-e6c814b09c1a")
                        },
                        new
                        {
                            Id = new Guid("4fb1e168-bf13-4702-9b61-0b8df2ef0c7d"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Golden Retriever",
                            SpeciesId = new Guid("f2d44dc6-6c6c-41d0-ad8d-e6c814b09c1a")
                        });
                });

            modelBuilder.Entity("Adoptrix.Core.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2d44dc6-6c6c-41d0-ad8d-e6c814b09c1a"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Dog"
                        },
                        new
                        {
                            Id = new Guid("c9c1836b-1051-45c3-a2c4-0d841e69e6d3"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Cat"
                        },
                        new
                        {
                            Id = new Guid("e6d11a53-bacb-4a8b-a171-beea7e935467"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Horse"
                        });
                });

            modelBuilder.Entity("Adoptrix.Core.Animal", b =>
                {
                    b.HasOne("Adoptrix.Core.Breed", "Breed")
                        .WithMany("Animals")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adoptrix.Core.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Adoptrix.Core.ImageInformation", "Images", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsProcessed")
                                .HasColumnType("bit");

                            b1.Property<string>("OriginalContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar");

                            b1.Property<DateTime>("UploadedAt")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(2)
                                .HasColumnType("datetime2(2)")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<Guid?>("UploadedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("AnimalId", "Id");

                            b1.ToTable("AnimalImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.Navigation("Breed");

                    b.Navigation("Images");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Adoptrix.Core.Breed", b =>
                {
                    b.HasOne("Adoptrix.Core.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Adoptrix.Core.Breed", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
