name: CI/CD Frontend

on:
  push:
    branches: main
    paths:
      - frontend/**
      - .github/workflows/cicd-frontend.yml
  pull_request:
    branches: main
    types:
      - opened
      - synchronize
      - reopened
      - closed
    paths:
      - frontend/**
      - .github/workflows/cicd-frontend.yml

jobs:
  # Build and deploy. Create preview environment for pull requests
  build_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: demo-frontend
    env:
      PROJECT_DIRECTORY: ${{ github.workspace }}/frontend
      BUILD_CONFIGURATION: demo
      BUILD_DIRECTORY: ${{ github.workspace }}/frontend/dist/browser
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install project dependencies
        run: npm ci
        working-directory: ${{ env.PROJECT_DIRECTORY }}

      # Build the client
      - name: Build client application
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: npx ng build --configuration ${{ env.BUILD_CONFIGURATION }}

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          production_branch: main
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          app_location: ${{ env.BUILD_DIRECTORY }}
          skip_app_build: true
          skip_api_build: true

  # Close the preview environment when the pull request is closed
  close_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close pull request
    environment: demo-frontend
    steps:
      - name: Remove preview environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          app_location: null # Unused in close pr step

  # Update CORS settings
  update_cors:
    name: Update CORS
    needs: [build_deploy, close_pr]
    if: ${{ always() }}
    uses: ./.github/workflows/update-cors.yml
    secrets:
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
