name: CI/CD Backend API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PUBLISH_RUNTIME: linux-x64

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    env:
      BACKEND_DIRECTORY: ${{ github.workspace }}/backend
      BUILD_CONFIGURATION: Release
      PUBLISH_DIRECTORY: ${{ github.workspace }}/publish
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Restore NuGet packages
      - name: Restore packages
        run: dotnet restore
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Publish API project
      - name: Publish API project
        run: >-
          dotnet publish
            --no-build
            --configuration ${{ env.BUILD_CONFIGURATION }}
            --runtime ${{ env.PUBLISH_RUNTIME }}
            --output ${{ env.PUBLISH_DIRECTORY }}
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Upload API artifact
      - name: Upload API artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-${{ env.PUBLISH_RUNTIME }}
          path: ${{ env.PUBLISH_DIRECTORY }}
