name: CI/CD Demo

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd.yml
      - src/**
      - tests/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd.yml
      - src/**
      - tests/**

env:
  JOBS_ARTIFACT_NAME: jobs

jobs:
  # Build, test and publish API job
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
      API_IMAGE_PATH: ${{ github.workspace }}/adoptrix-api.tar
      JOBS_PUBLISH_DIRECTORY: ${{ github.workspace }}/artifacts/jobs
      TEST_RESULTS_DIRECTORY: ${{ github.workspace }}/artifacts/test-results
    permissions:
      checks: write
      pull-requests: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Restore NuGet packages
      - name: Restore packages
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      # Run tests
      - name: Run tests
        run: >-
          dotnet test
          --no-build
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --logger trx
          --collect "XPlat Code Coverage"
          --settings coverlet.runsettings
          --results-directory ${{ env.TEST_RESULTS_DIRECTORY }}

      # Publish test results
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${{ env.TEST_RESULTS_DIRECTORY }}/*.trx
          check_name: Solution test results
          action_fail: true

      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ env.TEST_RESULTS_DIRECTORY }}

      # Upload coverage reports
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Publish jobs project
      - name: Publish jobs project
        #if: github.event_name != 'pull_request'
        run: >-
          dotnet publish src/Adoptrix.Jobs
          --no-build
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --output ${{ env.JOBS_PUBLISH_DIRECTORY }}

      # Upload jobs artifact
      - name: Upload jobs artifact
        #if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOBS_ARTIFACT_NAME }}
          path: ${{ env.JOBS_PUBLISH_DIRECTORY }}/*

  # Deploy main application job
  deploy_main_app:
    name: Deploy main application
    runs-on: ubuntu-latest
    needs: build
    #if: github.event_name != 'pull_request'
    permissions:
      id-token: write
      contents: read
    environment: demo
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Deploy Container App
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile.main
          acrName: ${{ vars.ACR_NAME }}
          imageToBuild: ${{ vars.ACR_NAME }}.azurecr.io/adoptrix-main:${{ github.sha }}
          containerAppName: ${{ vars.MAIN_CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.AZURE_RESOURCE_GROUP }}

  # Deploy jobs application
  deploy_jobs_app:
    name: Deploy jobs application
    runs-on: ubuntu-latest
    needs: build
    #if: github.event_name != 'pull_request'
    environment: demo
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.JOBS_ARTIFACT_NAME }}

      # Publish application
      - name: Publish application
        uses: Azure/functions-action@v1
        with:
          app-name: adoptrix-demo-jobs-func
          package: ${{ steps.download-artifact.outputs.download-path }}
          publish-profile: ${{ secrets.JOBS_PUBLISH_PROFILE }}
