name: CI/CD Frontend

on:
  push:
    branches: main
    paths:
      - frontend/**
      - .github/workflows/cicd-frontend.yml
  pull_request:
    branches: main
    types:
      - opened
      - synchronize
      - reopened
      - closed
    paths:
      - frontend/**
      - .github/workflows/cicd-frontend.yml

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: demo-frontend
    env:
      PROJECT_DIRECTORY: ${{ github.workspace }}/frontend
      BUILD_CONFIGURATION: demo
      BUILD_DIRECTORY: ${{ github.workspace }}/frontend/dist
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install project dependencies
        run: npm ci
        working-directory: ${{ env.PROJECT_DIRECTORY }}

      # Build the client
      - name: Build client application
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: npx ng build --configuration ${{ env.BUILD_CONFIGURATION }}

      # Copy static web app config
      - name: Copy static web app config
        run: cp ${{env.PROJECT_DIRECTORY}}/staticwebapp.config.json ${{env.BUILD_DIRECTORY}}

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: ${{ env.BUILD_DIRECTORY }}
          skip_app_build: true
          skip_api_build: true
