name: CI/CD Backend API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  API_ARTIFACT_NAME: backend-api

jobs:
  # Build, test and publish API job
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      BACKEND_DIRECTORY: ${{ github.workspace }}/backend
      BUILD_CONFIGURATION: Release
      PUBLISH_DIRECTORY: ${{ github.workspace }}/publish
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Restore NuGet packages
      - name: Restore packages
        run: dotnet restore
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Publish API project
      - name: Publish API project
        run: >-
          dotnet publish ${{ env.BACKEND_DIRECTORY }}/src/Adoptrix.Api
          --no-build
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --output ${{ env.PUBLISH_DIRECTORY }}
        working-directory: ${{ env.BACKEND_DIRECTORY }}

      # Upload API artifact
      - name: Upload API artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.API_ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

  # Deploy infrastructure job
  deploy_infra:
    name: Deploy infrastructure
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep template
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          deploymentName: main-cicd-backend-${{ github.run_number }}
          template: ${{ github.workspace }}/infra/main.bicep
          parameters: ${{ github.workspace }}/infra/main.bicepparam

  # Deploy application job
  deploy_api:
    name: Deploy application
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy_infra
    steps:
      # Download API artifact
      - name: Download API artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.API_ARTIFACT_NAME }}
