name: Continuous Integration / Deployment

on:
  push:
    branches:
      - main
      - feature/angular-frontend
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  # Build, test and publish API job
  build_backend:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
      API_PUBLISH_DIRECTORY: ${{ github.workspace }}/artifacts/api
      JOBS_PUBLISH_DIRECTORY: ${{ github.workspace }}/artifacts/jobs
      CLIENT_PUBLISH_DIRECTORY: ${{ github.workspace }}/artifacts/client
      TEST_RESULTS_DIRECTORY: ${{ github.workspace }}/artifacts/test-results
      CONTAINER_REGISTRY: ghcr.io
    permissions:
      checks: write
      contents: write
      packages: write
      pull-requests: write
    outputs:
      versionTag: ${{ steps.tag_commit.outputs.tag }}
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install .NET workloads
      - name: Install .NET workloads
        run: dotnet workload install aspire

      # Restore NuGet packages
      - name: Restore packages
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      # Run tests
      - name: Run tests
        run: >-
          dotnet test
          --no-build
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --logger trx
          --collect "XPlat Code Coverage"
          --settings coverlet.runsettings
          --results-directory ${{ env.TEST_RESULTS_DIRECTORY }}

      # Publish test results
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${{ env.TEST_RESULTS_DIRECTORY }}/*.trx
          check_name: Solution test results
          action_fail: true

      # Upload coverage reports
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Bump version and push tag
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        if: github.event_name != 'pull_request'
        id: tag_commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push API image
      - name: Build and push API image
        if: github.event_name != 'pull_request'
        run: >-
          dotnet publish src/Adoptrix.Api
          --configuration ${{ env.BUILD_CONFIGURATION }}
          -p:PublishProfile=DefaultContainer
          -p:Version=${{ steps.tag_commit.outputs.tag }}
          -p:ContainerRepository=${{ vars.API_REPOSITORY_NAME }}
          -p:ContainerRegistry=${{ env.CONTAINER_REGISTRY }}

      # Publish jobs project
      - name: Publish jobs project
        if: github.event_name != 'pull_request'
        run: >-
          dotnet publish src/Adoptrix.Jobs
          --no-build
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --output ${{ env.JOBS_PUBLISH_DIRECTORY }}

      # Upload jobs artifact
      - name: Upload jobs artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: jobs
          path: ${{ env.JOBS_PUBLISH_DIRECTORY }}/*

  build_frontend:
    name: Build and test frontend
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: ${{ github.workspace }}/frontend
      BUILD_CONFIGURATION: demo
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install project dependencies
        run: npm ci
        working-directory: ${{ env.PROJECT_DIRECTORY }}

      # Build the client
      - name: Build client application
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: npx ng build --configuration ${{ env.BUILD_CONFIGURATION }}

      # Upload client artifact
      - name: Upload client artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: ${{ env.PROJECT_DIRECTORY }}/dist/browser

  # Deploy demo apps
  deploy_demo_apps:
    name: Deploy demo apps
    if: github.event_name != 'pull_request' && github.ref_name == 'refs/heads/main'
    uses: ./.github/workflows/deploy-apps.yml
    needs:
      - build_backend
      - build_frontend
    with:
      environment: demo
      versionTag: v${{ needs.build_backend.outputs.versionTag }}
    secrets: inherit
