name: CI/CD Frontend

on:
  push:
    branches: main
    paths:
      - frontend/**
      - .github/workflows/cicd-frontend.yml
  pull_request:
    branches: main
    types:
      - opened
      - synchronize
      - reopened
      - closed
    paths:
      - frontend/**
      - .github/workflows/cicd-frontend.yml

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: demo-frontend
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend
          output_location: dist
