on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      versionTag:
        type: string
        required: true
      jobsArtifactName:
        type: string
        default: jobs
      clientArtifactName:
        type: string
        default: client

jobs:
  # Deploy infrastructure
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    outputs:
      apiAppName: ${{ steps.deploy_app.outputs.apiAppName }}
      functionAppName: ${{ steps.deploy_app.outputs.functionAppName }}
    env:
      ATTEMPT_ROLE_ASSIGNMENTS: false # GitHub Actions service principal does not have permissions to assign roles
      DEPLOYMENT_SUFFIX: -cicd-${{ github.run_number }}
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy shared resources
      - name: Deploy shared resources
        uses: azure/arm-deploy@v2
        id: deploy_shared
        with:
          scope: resourcegroup
          resourceGroupName: adoptrix-shared-rg
          template: ${{ github.workspace }}/deploy/infra/shared/main.bicep
          parameters: ${{ github.workspace }}/deploy/infra/shared/main.bicepparam
          deploymentName: main${{ env.DEPLOYMENT_SUFFIX }}
          failOnStdErr: false

      # Deploy app resources
      - name: Deploy app resources
        uses: azure/arm-deploy@v2
        id: deploy_app
        env:
          HIVE_IP_ADDRESS: ${{ secrets.HIVE_IP_ADDRESS }}
          ADOPTRIX_CONTAINER_REGISTRY: ghcr.io
          ADOPTRIX_CONTAINER_REGISTRY_USERNAME: frasermclean
          ADOPTRIX_API_IMAGE_REPOSITORY: ${{ vars.API_REPOSITORY_NAME }}
          ADOPTRIX_API_IMAGE_TAG: v${{ inputs.versionTag }}
        with:
          scope: resourcegroup
          resourceGroupName: adoptrix-${{ inputs.environment }}-rg
          deploymentName: main${{ env.DEPLOYMENT_SUFFIX }}
          template: ${{ github.workspace }}/deploy/infra/apps/main.bicep
          parameters: >-
            ${{ github.workspace }}/deploy/infra/apps/main.${{ inputs.environment }}.bicepparam
            keyVaultName=${{ steps.deploy_shared.outputs.keyVaultName }}
            appConfigurationName=${{ steps.deploy_shared.outputs.appConfigurationName }}
          failOnStdErr: false

  # Deploy jobs application
  deploy_jobs_app:
    name: Deploy jobs application
    runs-on: ubuntu-latest
    needs: deploy_infra
    permissions:
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.jobsArtifactName }}

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Publish application
      - name: Publish application
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.deploy_infra.outputs.functionAppName }}
          package: ${{ steps.download-artifact.outputs.download-path }}

  # Deploy client application
  deploy_client_app:
    name: Deploy client application
    runs-on: ubuntu-latest
    needs: deploy_infra
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    permissions:
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.clientArtifactName }}

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          production_branch: main
          azure_static_web_apps_api_token: ${{ secrets.CLIENT_DEPLOYMENT_TOKEN }}
          app_location: ${{ steps.download-artifact.outputs.download-path }}/wwwroot
          skip_app_build: true
          skip_api_build: true

  # Close pull request
  close_pr:
    name: Close pull request
    runs-on: ubuntu-latest
    needs: deploy_infra
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Remove preview environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
          azure_static_web_apps_api_token: ${{ secrets.CLIENT_DEPLOYMENT_TOKEN }}
          app_location: null
