on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      resourceGroup:
        type: string
        required: true
      apiAppName:
        type: string
        required: true
      jobsAppName:
        type: string
        required: true
      jobsArtifactName:
        type: string
        default: jobs
      clientArtifactName:
        type: string
        default: client

jobs:
  # Deploy container applications
  deploy_container_apps:
    name: Deploy container applications
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy API app
      - name: Deploy API app
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile.api
          acrName: ${{ vars.ACR_NAME }}
          imageToBuild: ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.API_REPOSITORY_NAME }}:${{ github.sha }}
          containerAppName: ${{ inputs.apiAppName }}
          resourceGroup: ${{ inputs.resourceGroup }}

  # Deploy jobs application
  deploy_jobs_app:
    name: Deploy jobs application
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.jobsArtifactName }}

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Publish application
      - name: Publish application
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.jobsAppName }}
          package: ${{ steps.download-artifact.outputs.download-path }}

  # Deploy client application
  deploy_client_app:
    name: Deploy client application
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.clientArtifactName }}

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          production_branch: main
          azure_static_web_apps_api_token: ${{ secrets.CLIENT_DEPLOYMENT_TOKEN }}
          app_location: ${{ steps.download-artifact.outputs.download-path }}/wwwroot
          skip_app_build: true
          skip_api_build: true
