name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - feature/container-apps-deploy-refactor
    paths:
      - .github/workflows/deploy-infra.yml
      - deploy/infra/**

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: demo
    permissions:
      id-token: write
      contents: read
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep template
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        env:
          ATTEMPT_ROLE_ASSIGNMENTS: false
          HIVE_IP_ADDRESS: ${{ secrets.HIVE_IP_ADDRESS }}
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          deploymentName: main-deploy-${{ github.run_number }}
          template: ${{ github.workspace }}/deploy/infra/main.bicep
          parameters: ${{ github.workspace }}/deploy/infra/main.demo.bicepparam
