name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-infra.yml
      - deploy/infra/**

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: demo
    permissions:
      id-token: write
      contents: read
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Get latest API image tag
      - name: Get latest API image tag
        run: |
          IMAGE_TAG=$(az acr repository show-tags --name ${{ vars.ACR_NAME }} --repository ${{ vars.API_REPOSITORY_NAME }} --orderby time_desc --top 1 --output tsv)
          echo "Latest API image tag: $IMAGE_TAG"
          echo "ADOPTRIX_API_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Deploy Bicep template
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v2
        env:
          ATTEMPT_ROLE_ASSIGNMENTS: false
          HIVE_IP_ADDRESS: ${{ secrets.HIVE_IP_ADDRESS }}
          ADOPTRIX_API_IMAGE_REPOSITORY: ${{ vars.API_REPOSITORY_NAME }}
          ADOPTRIX_API_IMAGE_TAG: ${{ env.ADOPTRIX_API_IMAGE_TAG }}
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          deploymentName: main-deploy-${{ github.run_number }}
          template: ${{ github.workspace }}/deploy/infra/main.bicep
          parameters: ${{ github.workspace }}/deploy/infra/main.demo.bicepparam
